### ISSUE TITLE
Asset_packs Store a large file font to prompt insufficient memory

### ISSUE THREAD

**Issue by bug508** [Next-Flip/Momentum-Firmware#102]
### Describe the enhancement you're suggesting.

I generated a Secondary.u8f file with a file size of 61.4KB When the Asset Pack loads, I get an out-of-memory warning. Is it possible to load the font index first when loading the font file, and then go to the SD card to read the dot matrix information which dot matrix is used
[Secondary.zip](https://github.com/Next-Flip/Momentum-Firmware/files/15041185/Secondary.zip)

**Comment by WillyJL** [comment]
Not possible, sd card is too slow and ram too small. We can't do much else than keep the font in ram, you will need to make the font smaller. I haven't looked at your font file, but by that size I presume you included non-ascii characters, might be a good idea to remove those. If I remember correctly, bdfconv supported a custom glyph internal, I don't remember the name of the command line switch, but you should select 32-127 interval since that's the printable ascii character set. That will usually yield a 1-4kb font file, which should be fine.
