### ISSUE TITLE
Frequency Analyser on Momentum Firmware

### ISSUE THREAD

**Issue by askbriancai** [Next-Flip/Momentum-Firmware#145]
Hi, i just flashed the latest release of the Momentum Firmware.

When using the Sub-ghz frequency analyser, i do not receive any frequency readings at all.
the default sub-ghz read function registers as per normal. 

is there a fix i can implement please?

**Comment by WillyJL** [comment]
lower the threshold value by pressing the left button

**Comment by WillyJL** [comment]
Also consider that maybe there is simply no signal to detect. Frequency analyzer is intended to find out frequency of a signal you are controlling, like pressing a remote button and seeing what frequency it is. While it can happen, do not expect to receive random frequency detections when passively using it. Other than that, your issue is most likely setting the wrong threshold. Comment if you have more doubts, I will close this for the time being due to being most likely user error.
