### ISSUE TITLE
[question] is the app loading slower than before ?

### ISSUE THREAD

**Issue by ddcxcy6q5** [Next-Flip/Momentum-Firmware#154]
Why has app loading become so slow and am I the only one experiencing that ?
Also if I remember well, there was an update that made the application loading noticeably faster but maybe I'm wrong.

**Comment by Willy-JL** [comment]
A long time ago fastfap made faps load nearly instantly. However after the gap is loaded, the app itself needs to initialize what it needs. Your question has no answer by itself, it depends on what app you mean. Subghz needs to check for an external module, it has done that for a very long time. Nfc recently was changed to load plugins when opened, instead of when loading files: previously, it would load plugins when choosing a saved file, and that would feel very sluggish, now the cache is loaded when opening the app so it takes a little longer (a few seconds) but it means that opening saved files and reading tags is much faster.

**Comment by ddcxcy6q5** [comment]
Thank you for your answer !

Should I close the issue ?

**Comment by Willy-JL** [comment]
It's a bit annoying that it's slower to open it, but at the end of the day the plugins need to be cached anyway, so either slower open or slower file loading, total time to use is the same (and actually, I believe that previously it loaded the cache when opening every file, so it was always slow opening files, not just the first one)

**Comment by Willy-JL** [comment]
I might update the changelog to mention that it loads files faster, at the expense of opening the app a bit slower
