### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by Sarah831o** [Next-Flip/Momentum-Firmware#23]
### Describe the bug.

installing firmware and stuck on updating resources

### Reproduction

-

**Comment by WillyJL** [comment]
How long has it been stuck? It takes about 5 minutes overall to install if not more

**Comment by Ghost6220** [comment]
Mine was stuck loading as well.  I tried installing today. I ended up disconnecting after 20 minutes

**Comment by WillyJL** [comment]
was it on flipper or on the website/qflipper that it got stuck?

**Comment by UberGuidoZ** [comment]
It your SD card is loaded up with conflicting stuff, I’ve run into issues before. Try wiping the SD, installing Official, then upgrading to Momentum. Lastly, installing directly from the Flipper via a TGZ file can sometimes help.

**Comment by Ghost6220** [comment]
I tried installing through web. I'll give the other way a shot.

**Comment by WillyJL** [comment]
as i asked, was it stuck on flipper as "updating resources", or was it stuck on web at "resources.tar"? they are different. one of them has an ongoing issue from OFW. please answer.

**Comment by WillyJL** [comment]
if it was stuck on flipper as "updating resources", then the problem is likely with the sd card. try rebooting, or formatting it.

if it stuck on web or qflipper at "resources.tar", then the problem is likely with USB CDC parameters. see #40.

closing as stale. feel free to comment with more info, but the above should likely cover most cases.
