### ISSUE TITLE
repetaed bus fault & out of ram crashes

### ISSUE THREAD

**Issue by GameLord2011** [Next-Flip/Momentum-Firmware#234]
### Describe the bug.

I randomly get "Bus Fault" and "Out of Ram" crashes.
How do I fix this?

### Reproduction

I can't rember.

### Target

Hardware? (idk)

**Comment by WillyJL** [comment]
Flipper hardware is very limited and we are pushing it to its limits. Simply, it's running out of ram. What you can try is changing what asset pack your using, since asset packs containing icons and fonts will consume some ram in background. Also some third party apps are coded a bit poorly and will leak memory, so after a while of using a flipper, a out of memory crash is normal. If you can reproduce a crash consistently, and disabled asset packs, then you might have a bug on your hands by we can try to fix.

**Comment by GameLord2011** [comment]
k
it usually happens when using the nfc app

**Comment by AztecCodes** [comment]
Yes the issue with the NFC App is known. It was already reported.

Check the issue here in the Unleashed Repo: https://github.com/DarkFlippers/unleashed-firmware/issues/778
The issue was also reported in Momentum Repo here: https://github.com/Next-Flip/Momentum-Firmware/issues/144

Using the Flipper Zero and then starting the NFC App can lead to Bus Fault or Out of RAM Errors.

**Comment by Helios343** [comment]
Ohhh I see if your using one of those modules just be aware that that they
can short out on the antenna connection there onto the board

**Comment by FalsePhilosopher** [comment]
Hold your back arrow for the quick power off function, does it display the crying dolphin or just turn off power? Yesterday I upgraded from 75e to 78e and the issue persisted. I noticed the different power off menu and went about fixing it. Rebooted into DFU mode, repaired to 1.0.1 from qflipper, once it booted after install I formatted the sd card. I then installed 78e from qflipper and I got my crying dolphin back an it doesn't crash launching files from explorer. I have not done extensive testing, just launched a file from browser and micro python which crashed with a bus error the first time but launched the second time. I came to the UL issue to report my findings and figured I would mirror them here as well.
Edit: After a crash using the change name function and rebooting I don't have the crying dolphin anymore, maybe it's just because I switched from bt screen sharing to an android qflipper instance to usb linux qflipper it's a different screen idk. My screen is broken, so I need to use some form of display forwarding to use my fz.

**Comment by GameLord2011** [comment]
r u using dev? im using release.

**Comment by GameLord2011** [comment]
wait that is ofw

**Comment by GameLord2011** [comment]
that's an ofw release @FalsePhilosopher

**Comment by GameLord2011** [comment]
1.0.1

**Comment by GameLord2011** [comment]
also, @Helios343 im using internal modules

**Comment by Helios343** [comment]
Sorry there was a error on my end that message wasn't ment to be in this
thread

**Comment by GameLord2011** [comment]
💡 you could unload anything that isn't currently being used

**Comment by WillyJL** [comment]
Which is what happens?

**Comment by GameLord2011** [comment]
*Forehead slap*
