### ISSUE TITLE
Can we add FlipperNested functionality

### ISSUE THREAD

**Issue by Kaisir** [Next-Flip/Momentum-Firmware#251]
### Description of the feature you're suggesting.

https://github.com/AloneLiberty/FlipperNested
This open-source project can quickly resolve IC card vulnerabilities and is very user-friendly. Can it be adapted? thank you.

**Comment by WillyJL** [comment]
mntm-007 and previous releases include flipper nested. devbuilds already include, and mntm-008 will include as a consequence, the work by noproto in OFW PR 3822 which builds nested directly into the main NFC app. i have removed flipper nested since it is now useless, simply use the NFC app which runs the same, and many more advanced, attacks.
