### ISSUE TITLE
Adding native Python support

### ISSUE THREAD

**Issue by mbcraft-exe** [Next-Flip/Momentum-Firmware#71]
### Description of the feature you're suggesting.

I saw that there's no native way to execute Python scripts like it's possible to do with JS.
So I wanted to suggest to add Python native running on firmeware.

**Comment by WillyJL** [comment]
unfortunately not really possible. mJS, which is what the flipper JS runner is using under the hood, takes up about 50kb of flash space and 1kb or ram. micropython takes about 256kb of flash space and 16kb of ram. the ram side would be acceptable, but flash space not at all. the internal flash space is full to the brim, we cannot fit much of anything into it anymore, especially not a 256kb blob. fitting mJS was already a challenge for custom firmwares like us, due to the additional features we have that take up space on flash. currently, we have 56kb total of "free" flash, which is without counting the files stored in internal storage. there is a hard limit of keeping atleast 28kb of flash, since any less than that will start to cause issues for installing the firmware. and making a micropython app/fap is not possible either, because the ram is 256kb total, with about half of it filled all the time, so basically 128kb (if not less) of usable ram, which would need to fit 256kb of micropython code...

and even if somehow it were barely possible, there is already JS support, having python too would bring absolutely no advantage besides the different syntax, and that alone is not worth having 2 of the same thing. sorry, but not gonna happen.
