### ISSUE TITLE
App udate info

### ISSUE THREAD

**Issue by lordrak007** [Next-Flip/Momentum-Firmware#77]
### Describe the enhancement you're suggesting.

Hi, thank you for adding awesome features. But it is possiblle add some sescription to every added function? Like Repeater in subghz. Hot it works? Usage?
Thank you very much
Lordrak

**Comment by WillyJL** [comment]
putting documentation in every feature right in the firmware is not feasible from a UI/UX point of view, and keeping documentation for all features is a big task and it comes secondary to the actual development of the firmware. we try to make everything as intuitive as possible and provide examples where relevant. if all else fails, in most cases when the feature was added initially it had an explanation in the changelog.

to answer your question, subghz repeater is a mode where received signals will be transmitted right away. instead of receiving and seeing the signal, it is sent again without remembering it.
